spring.application.name=myfarm-worker

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.data.redis.repositories.enabled=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=never
management.metrics.tags.application=${spring.application.name}
